name: pypi publish ci

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install deps
        run: |
          python -m pip install poetry
          poetry install
      - name: pytest
        run: |
          poetry run pytest
      - name: build
        run: |
          poetry build
      - name: publish
        run: poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
